services:
  php-fpm:
    container_name: php-fpm-test
    user: www-data
    build:
      context: ./php-fpm
      dockerfile: Dockerfile:${PHP_VERSION:-8.3}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-magento}
      - MYSQL_USER=${MYSQL_USER:-magento}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-magento}
    volumes:
      - ./php-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
      - ./php-fpm/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini:ro
    depends_on:
      - mysql
      - opensearch
      - selenium
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -S http://localhost || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  mysql:
    container_name: mysql-test
    image: mysql:${MYSQL_VERSION:-8.0}
    environment:
      - MYSQL_USER=${MYSQL_USER:-magento}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-magento}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-magento}
      - log_bin_trust_function_creators=1
    tmpfs:
      - /tmp
      - /var/lib/mysql

  opensearch:
    container_name: opensearch-test
    build:
      context: ./opensearch
      args:
        - OPENSEARCH_VERSION=${OPENSEARCH_VERSION:-1.2.3}
    environment:
      - cluster.name=opensearch-cluster
      - discovery.type=single-node
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"

  selenium:
    image: selenium/standalone-firefox
    container_name: selenium-test
    shm_size: 2gb
    ports:
      - "4444:4444"

  magento-coding-standard:
    container_name: magento-coding-standard-test
    build:
      context: ./magento-coding-standard
      args:
        - MAGENTO_CODING_STANDARD_VERSION=${MAGENTO_CODING_STANDARD_VERSION:-33}