services:
  php-fpm:
    container_name: php-fpm-test
    user: www-data
    build:
      context: ./php-fpm
      dockerfile: Dockerfile:${PHP_VERSION:-8.3}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-magento}
      - MYSQL_USER=${MYSQL_USER:-magento}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-magento}
      - MAGENTO_PUBLIC_KEY=${MAGENTO_PUBLIC_KEY}
      - MAGENTO_PRIVATE_KEY=${MAGENTO_PRIVATE_KEY}
      - MAGENTO_VERSION=${MAGENTO_VERSION}
    volumes:
      - ./php-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
      - ./php-fpm/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini:ro
    depends_on:
      - mysql
      - opensearch
      - rabbitmq

  mysql:
    container_name: mysql-test
    image: mysql:${MYSQL_VERSION:-8.0}
    environment:
      - MYSQL_USER=${MYSQL_USER:-magento}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-magento}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-magento}
      - log_bin_trust_function_creators=1
    tmpfs:
      - /tmp
      - /var/lib/mysql

  opensearch:
    container_name: opensearch-test
    image: ghcr.io/rickdaalhuizen90/opensearch:${OPENSEARCH_VERSION:-2.12.0}
    environment:
      - cluster.name=opensearch-cluster
      - discovery.type=single-node
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
