services:
  php-fpm:
    container_name: php-fpm-test
    user: www-data
    build:
      context: ./php-fpm
      args:
        PHP_VERSION: ${PHP_VERSION:-8.3}
        COMPOSER_VERSION: ${COMPOSER_VERSION:-2.1.3}
    volumes:
      ./php-fpm/custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro
      ./php-fpm/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini:ro
    depends_on:
      - mysql
      - opensearch
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -S http://localhost || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  mysql:
    container_name: mysql-test
    image: mysql:8.0
    environment:
      MYSQL_USER: ${MYSQL_USER:-magento}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-magento}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-magento}
    tmpfs:
      - /tmp
      - /var/lib/mysql

  opensearch:
    container_name: opensearch-test
    build:
      context: ./opensearch
      args:
        OPENSEARCH_VERSION: ${OPENSEARCH_VERSION:-1.2.3}
    environment:
      - cluster.name=opensearch-cluster
      - discovery.type=single-node
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
